import type {
  Service, TeamMember, Testimonial, BlogPost,
  FAQ, GalleryItem, Stat, ProcessStep, Industry,
  NavItem, ContactInfo,
} from '@/types'

export const SERVICES: Service[] = [
  {
    id: 'nabh-consultancy',
    title: 'NABH Accreditation',
    description: 'Expert guidance through the complete NABH accreditation process. We have successfully accredited 200+ hospitals across India with a 98% first-attempt success rate.',
    icon: 'Award',
    features: ['Gap Analysis & Assessment', 'Documentation Support', 'Staff Training Programs', 'Mock Survey & Audit'],
    slug: 'nabh-accreditation',
    category: 'hospital',
  },
  {
    id: 'hospital-licensing',
    title: 'Hospital Licensing',
    description: 'End-to-end assistance with hospital licensing, registrations, and regulatory compliance across all Indian states.',
    icon: 'FileCheck',
    features: ['State Licensing', 'Central Registrations', 'Compliance Management', 'Legal Documentation'],
    slug: 'hospital-licensing',
    category: 'hospital',
  },
  {
    id: 'medical-equipment',
    title: 'Medical Equipment Procurement',
    description: 'Strategic procurement of world-class medical equipment with quality assurance, vendor evaluation, and cost optimization.',
    icon: 'Stethoscope',
    features: ['Vendor Evaluation', 'Cost Optimization', 'Quality Assurance', 'Installation Support'],
    slug: 'medical-equipment',
    category: 'hospital',
  },
  {
    id: 'healthcare-recruitment',
    title: 'Healthcare Recruitment',
    description: 'Specialized recruitment services for doctors, nurses, paramedics, and administrative healthcare professionals.',
    icon: 'Users',
    features: ['Doctor Placement', 'Nursing Staff', 'Paramedic Hiring', 'Admin & Support Staff'],
    slug: 'healthcare-recruitment',
    category: 'hospital',
  },
  {
    id: 'medical-tourism',
    title: 'Medical Tourism',
    description: 'International patient facilitation and medical tourism infrastructure development for healthcare facilities.',
    icon: 'Globe',
    features: ['International Patients', 'Travel Coordination', 'Interpreter Services', 'Post-Care Support'],
    slug: 'medical-tourism',
    category: 'hospital',
  },
  {
    id: 'hospital-management',
    title: 'Hospital Management',
    description: 'Comprehensive hospital operations management, workflow optimization, and performance improvement consulting.',
    icon: 'Building2',
    features: ['Operations Audit', 'Process Optimization', 'Performance Metrics', 'Revenue Enhancement'],
    slug: 'hospital-management',
    category: 'hospital',
  },
  {
    id: 'digital-healthcare',
    title: 'Digital Healthcare Solutions',
    description: 'Complete digital transformation for healthcare facilities — from HIS and EMR implementation to telemedicine.',
    icon: 'Monitor',
    features: ['HIS Implementation', 'EMR Systems', 'Telemedicine Setup', 'Digital Training'],
    slug: 'digital-healthcare',
    category: 'hospital',
  },
  {
    id: 'business-strategy',
    title: 'Business Strategy',
    description: 'Strategic business planning, market entry analysis, and growth consulting for healthcare enterprises and startups.',
    icon: 'TrendingUp',
    features: ['Market Analysis', 'Business Planning', 'Growth Strategy', 'Investor Relations'],
    slug: 'business-strategy',
    category: 'business',
  },
  {
    id: 'government-projects',
    title: 'Government Projects',
    description: 'Expert assistance with Ayushman Bharat empanelment, government healthcare schemes, and public health initiatives.',
    icon: 'Landmark',
    features: ['Ayushman Bharat', 'State Health Schemes', 'Tender Management', 'Policy Compliance'],
    slug: 'government-projects',
    category: 'business',
  },
  {
    id: 'ngo-consultancy',
    title: 'NGO Consultancy',
    description: 'Complete support for healthcare NGO setup, FCRA registration, CSR alignment, and community health programs.',
    icon: 'Heart',
    features: ['NGO Registration', 'CSR Alignment', 'Grant Applications', 'Program Design'],
    slug: 'ngo-consultancy',
    category: 'business',
  },
  {
    id: 'startup-advisory',
    title: 'Healthcare Startup Advisory',
    description: 'Mentorship and advisory for healthcare startups covering regulatory hurdles and go-to-market strategy.',
    icon: 'Rocket',
    features: ['Regulatory Guidance', 'Business Mentoring', 'Network Access', 'Funding Support'],
    slug: 'startup-advisory',
    category: 'business',
  },
  {
    id: 'hospital-consultancy',
    title: 'Hospital Project Consultancy',
    description: 'Full-spectrum consultancy for greenfield hospital projects, expansions, and turnaround of underperforming facilities.',
    icon: 'Briefcase',
    features: ['Greenfield Projects', 'Expansion Planning', 'Turnaround Strategy', 'Operational Excellence'],
    slug: 'hospital-consultancy',
    category: 'hospital',
  },
]

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Dr. Rajesh Kumar',
    role: 'CEO & Founder',
    bio: 'With 20+ years in healthcare management, Dr. Kumar founded FeedIndia to democratize quality healthcare consultancy across India.',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&q=80',
    linkedin: 'https://linkedin.com',
    specialization: 'Hospital Administration & Strategy',
  },
  {
    id: 'tm-2',
    name: 'Ms. Priya Sharma',
    role: 'Chief Operating Officer',
    bio: 'Priya oversees all operational excellence initiatives. Her Six Sigma background has helped 150+ hospitals achieve 30–40% efficiency gains.',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
    linkedin: 'https://linkedin.com',
    specialization: 'Operations & Process Excellence',
  },
  {
    id: 'tm-3',
    name: 'Dr. Anil Mehta',
    role: 'Chief Medical Advisor',
    bio: 'A senior physician with expertise in clinical governance and quality management, Dr. Mehta has personally led NABH accreditation for 80+ hospitals.',
    image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&q=80&auto=format&fit=crop',
    linkedin: 'https://linkedin.com',
    specialization: 'Clinical Governance & NABH',
  },
  {
    id: 'tm-4',
    name: 'Ms. Sunita Patel',
    role: 'Head of NABH Accreditation',
    bio: 'Sunita is a certified NABH assessor with a decade of experience guiding hospitals through accreditation cycles.',
    image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&q=80&auto=format&fit=crop',
    linkedin: 'https://linkedin.com',
    specialization: 'NABH & Quality Systems',
  },
  {
    id: 'tm-5',
    name: 'Mr. Vikram Singh',
    role: 'Director, Digital Healthcare',
    bio: 'A tech entrepreneur turned healthcare innovator, Vikram has implemented HIS and telemedicine in 70+ hospitals across tier 2 and 3 cities.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    linkedin: 'https://linkedin.com',
    specialization: 'Health IT & Telemedicine',
  },
  {
    id: 'tm-6',
    name: 'Mr. Arjun Verma',
    role: 'Head of Business Development',
    bio: 'Arjun leads client acquisition and partnership strategy with a network spanning 500+ hospitals and government health departments.',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&q=80',
    linkedin: 'https://linkedin.com',
    specialization: 'Business Growth & Partnerships',
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Dr. Suresh Agarwal',
    role: 'Medical Director',
    company: 'Sunrise Multispecialty Hospital, Pune',
    content: 'FeedIndia guided us through our NABH accreditation seamlessly. Their deep expertise made a complex process feel effortless. We achieved accreditation in just 8 months — well ahead of schedule.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=200&q=80',
  },
  {
    id: 'test-2',
    name: 'Ms. Kavitha Nair',
    role: 'CEO',
    company: 'HealthFirst Clinic Chain, Kerala',
    content: 'The hospital licensing support from FeedIndia saved us months of back-and-forth with regulatory authorities. Their team knows exactly what documentation is needed. Highly recommended.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80',
  },
  {
    id: 'test-3',
    name: 'Mr. Ramesh Gupta',
    role: 'Chairman',
    company: 'Dhanwantari Hospital Group, Rajasthan',
    content: 'We engaged FeedIndia for medical equipment procurement and saved over 22% on our total equipment budget without compromising on quality. Their vendor network is exceptional.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80',
  },
  {
    id: 'test-4',
    name: 'Dr. Meena Krishnamurthy',
    role: 'Founder & CMO',
    company: 'CarePoint Diagnostics, Bangalore',
    content: 'Their digital healthcare team implemented our entire HIS and patient portal in 3 months. The transition was smooth and staff adapted quickly thanks to their excellent training.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=200&q=80',
  },
  {
    id: 'test-5',
    name: 'Mr. Pradeep Shah',
    role: 'Managing Trustee',
    company: 'Arogya Seva NGO, Gujarat',
    content: 'FeedIndia helped us structure our community health NGO from scratch — registration, FCRA, CSR partnerships, and program design. We are now running health camps in 40+ villages.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=80',
  },
  {
    id: 'test-6',
    name: 'Dr. Anita Joshi',
    role: 'Founder',
    company: 'MedTech Startup, Hyderabad',
    content: 'FeedIndia\'s startup advisory gave us a clear regulatory roadmap and investor introductions. We closed our seed round within 6 months of engaging them.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80',
  },
]

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'The Complete Guide to NABH Accreditation in 2024',
    excerpt: 'Everything you need to know about NABH standards, timelines, documentation requirements, and how to achieve first-attempt accreditation for your hospital.',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
    category: 'NABH',
    date: '2024-11-15',
    readTime: 12,
    author: 'Dr. Anil Mehta',
    slug: 'complete-guide-nabh-accreditation-2024',
  },
  {
    id: 'blog-2',
    title: 'Hospital Digitalization: Why HIS is Non-Negotiable in 2025',
    excerpt: 'Hospitals without a robust HIS are losing revenue and patient trust. Here is why and how to digitalize effectively.',
    image: 'https://images.unsplash.com/photo-1551601651-2a8555bfb10d?w=800&q=80&auto=format&fit=crop',
    category: 'Digital Health',
    date: '2024-10-28',
    readTime: 8,
    author: 'Mr. Vikram Singh',
    slug: 'hospital-digitalization-his-2025',
  },
  {
    id: 'blog-3',
    title: "India's Medical Tourism Boom: How to Position Your Hospital",
    excerpt: 'India is projected to become a $13 billion medical tourism market by 2026. Learn the exact steps to attract international patients.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec0?w=800&q=80',
    category: 'Medical Tourism',
    date: '2024-10-10',
    readTime: 10,
    author: 'Dr. Rajesh Kumar',
    slug: 'india-medical-tourism-boom-hospital-positioning',
  },
  {
    id: 'blog-4',
    title: 'Ayushman Bharat Empanelment: A Step-by-Step Checklist',
    excerpt: 'Getting empanelled under PMJAY can transform your hospital\'s revenue. This checklist covers every requirement and process step.',
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800&q=80',
    category: 'Government Schemes',
    date: '2024-09-22',
    readTime: 7,
    author: 'Ms. Priya Sharma',
    slug: 'ayushman-bharat-empanelment-checklist',
  },
  {
    id: 'blog-5',
    title: 'Top 10 Mistakes Hospitals Make During Licensing',
    excerpt: 'Licensing delays are costly. We analyzed 300+ hospital licensing projects to identify the most common mistakes and how to avoid them.',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80',
    category: 'Hospital Licensing',
    date: '2024-09-05',
    readTime: 9,
    author: 'Ms. Sunita Patel',
    slug: 'top-10-mistakes-hospital-licensing',
  },
  {
    id: 'blog-6',
    title: 'Building a Healthcare Startup in India: Regulatory Roadmap',
    excerpt: 'From CDSCO approvals to state licensing, the Indian healthcare regulatory landscape is complex. This guide maps out the complete journey.',
    image: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&q=80',
    category: 'Startups',
    date: '2024-08-18',
    readTime: 11,
    author: 'Mr. Arjun Verma',
    slug: 'healthcare-startup-india-regulatory-roadmap',
  },
]

export const FAQS: FAQ[] = [
  { id: 'faq-1', question: 'How long does the NABH accreditation process take?', answer: 'Typically 6–12 months depending on your hospital\'s current quality systems. With FeedIndia\'s guidance, most clients achieve accreditation within 8–10 months. We start with a gap analysis and build a customized roadmap.', category: 'NABH' },
  { id: 'faq-2', question: 'What is the approximate cost of NABH consultancy?', answer: 'Our fees are customized based on bed strength, quality maturity, and scope. We offer transparent, milestone-based pricing with no hidden charges. Contact us for a free initial assessment and quote.', category: 'NABH' },
  { id: 'faq-3', question: 'Do you provide services across all states in India?', answer: 'Yes, FeedIndia operates pan-India with active projects in 15+ states including Maharashtra, Karnataka, Tamil Nadu, Gujarat, Rajasthan, UP, Delhi NCR, West Bengal, and more.', category: 'General' },
  { id: 'faq-4', question: 'What documents are required for hospital licensing?', answer: 'Requirements vary by state but typically include land/building ownership proof, architectural approvals, fire NOC, biomedical waste authorization, medical director qualifications, staff register, and equipment list. Our team handles the complete checklist.', category: 'Licensing' },
  { id: 'faq-5', question: 'Can you help with both new hospital setup and existing hospital improvement?', answer: 'Absolutely. We work with greenfield projects from concept to commissioning, as well as established hospitals undergoing expansion, accreditation, digitalization, or performance turnaround.', category: 'General' },
  { id: 'faq-6', question: 'What is your NABH success rate?', answer: 'We maintain a 98% first-attempt NABH accreditation success rate across 200+ hospitals, achieved through rigorous preparation methodology and dedicated on-site survey support.', category: 'NABH' },
  { id: 'faq-7', question: 'Do you offer healthcare staff recruitment services?', answer: 'Yes. Our recruitment vertical places doctors across all specialties, nurses, paramedics, radiographers, lab technicians, and administrative staff from a database of 50,000+ verified professionals.', category: 'Recruitment' },
  { id: 'faq-8', question: 'How does FeedIndia help with Ayushman Bharat empanelment?', answer: 'We handle the complete empanelment process: eligibility assessment, documentation, portal registration, inspection preparation, and post-empanelment claim management training.', category: 'Government' },
  { id: 'faq-9', question: 'What is the process to engage FeedIndia?', answer: '(1) Contact us for a free 30-min discovery call. (2) We conduct a needs assessment. (3) We share a tailored proposal. (4) Upon agreement, a dedicated project manager begins within 3 working days.', category: 'Process' },
  { id: 'faq-10', question: 'Do you assist healthcare NGOs and trusts?', answer: 'Yes. Our NGO division helps healthcare trusts with registration, FCRA, 80G/12A exemptions, CSR fund applications, and community health program design. We have supported 45+ healthcare NGOs.', category: 'NGO' },
]

export const GALLERY_ITEMS: GalleryItem[] = [
  { id: 'g-1', src: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&q=80', alt: 'Modern hospital building', category: 'hospitals', title: 'Sunrise Multispecialty Hospital, Pune' },
  { id: 'g-2', src: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&q=80', alt: 'Hospital reception', category: 'hospitals', title: 'Patient-friendly reception design' },
  { id: 'g-3', src: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=800&q=80&auto=format&fit=crop', alt: 'Medical team meeting', category: 'office', title: 'Team strategy session' },
  { id: 'g-4', src: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80', alt: 'Doctor consultation', category: 'hospitals', title: 'Doctor-patient consultation' },
  { id: 'g-5', src: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=800&q=80', alt: 'Medical equipment', category: 'projects', title: 'Medical equipment procurement' },
  { id: 'g-6', src: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800&q=80&auto=format&fit=crop', alt: 'Healthcare training', category: 'projects', title: 'Staff training workshop' },
  { id: 'g-7', src: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80&auto=format&fit=crop', alt: 'Operation theatre', category: 'hospitals', title: 'OT setup consultancy' },
  { id: 'g-8', src: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80', alt: 'Hospital ward', category: 'hospitals', title: 'ICU & ward planning' },
  { id: 'g-9', src: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80', alt: 'Healthcare team', category: 'office', title: 'FeedIndia consultant team' },
]

export const STATS: Stat[] = [
  { label: 'Years Experience', value: '15', suffix: '+', icon: 'Calendar' },
  { label: 'Projects Completed', value: '500', suffix: '+', icon: 'CheckCircle' },
  { label: 'Hospitals Supported', value: '200', suffix: '+', icon: 'Building2' },
  { label: 'Doctors Served', value: '1000', suffix: '+', icon: 'Users' },
  { label: 'Success Rate', value: '98', suffix: '%', icon: 'TrendingUp' },
]

export const PROCESS_STEPS: ProcessStep[] = [
  { step: 1, title: 'Initial Consultation', description: 'Free 30-minute discovery call to understand your needs, current state, and goals.', icon: 'MessageCircle' },
  { step: 2, title: 'Planning & Proposal', description: 'Detailed needs assessment followed by a customized scope, timeline, and pricing proposal.', icon: 'ClipboardList' },
  { step: 3, title: 'Documentation', description: 'Our experts prepare all required documentation, policies, SOPs, and compliance records.', icon: 'FileText' },
  { step: 4, title: 'Review & Approval', description: 'Mock audits, gap corrections, and full preparation for regulatory submission or survey.', icon: 'CheckSquare' },
  { step: 5, title: 'Execution', description: 'Implementation support, on-site presence during surveys, and real-time issue resolution.', icon: 'Zap' },
  { step: 6, title: 'Ongoing Support', description: 'Post-project monitoring, re-accreditation planning, and continued advisory relationship.', icon: 'LifeBuoy' },
]

export const INDUSTRIES: Industry[] = [
  { title: 'Hospitals & Medical Centers', description: 'Multi-specialty, super-specialty, and single-specialty hospitals across all bed strengths.', icon: 'Building2', count: '120+ Clients' },
  { title: 'Clinics & Polyclinics', description: 'Day-care surgery centers, OPD clinics, and multi-doctor polyclinics.', icon: 'Stethoscope', count: '250+ Clients' },
  { title: 'Diagnostic Centers', description: 'Radiology centers, pathology labs, and integrated diagnostic chains.', icon: 'FlaskConical', count: '80+ Clients' },
  { title: 'Healthcare NGOs', description: 'Non-profits, charitable trusts, and community health organizations.', icon: 'Heart', count: '45+ Clients' },
  { title: 'Healthcare Startups', description: 'Health-tech, med-tech, and clinical service startups at seed to Series B stage.', icon: 'Rocket', count: '60+ Clients' },
  { title: 'Medical Colleges', description: 'MBBS, BDS, nursing, and paramedic colleges seeking NMC compliance.', icon: 'GraduationCap', count: '35+ Clients' },
]

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', href: '/#hero' },
  {
    label: 'Services',
    href: '/#services',
    children: [
      { label: 'NABH Accreditation', href: '/#services' },
      { label: 'Hospital Licensing', href: '/#services' },
      { label: 'Medical Equipment', href: '/#services' },
      { label: 'Healthcare Recruitment', href: '/#services' },
      { label: 'Hospital Management', href: '/#services' },
      { label: 'Digital Healthcare', href: '/#services' },
      { label: 'Business Strategy', href: '/#services' },
      { label: 'Government Projects', href: '/#services' },
    ],
  },
  { label: 'About', href: '/#about' },
  { label: 'Process', href: '/#process' },
  { label: 'Blog', href: '/#blog' },
  { label: 'Contact', href: '/#contact' },
]

export const CONTACT_INFO: ContactInfo = {
  phone: '+91 98765 43210',
  email: 'info@feedindiahealthcare.com',
  whatsapp: '919876543210',
  address: '123 Healthcare Hub, Sector 18, Noida, Uttar Pradesh – 201301',
  workingHours: 'Mon–Sat: 9:00 AM – 6:00 PM',
}
